### PR TITLE
fix(put): pass CID options to resolver

### PR DESCRIPTION
**Pull request by richardschneider**
Creating the CID allows `version` and `hashAlg` to be specified; see #82.

### CODE REVIEW

**Comment by richardschneider** [comment]
This PR is blocked on https://github.com/ipld/interface-ipld-format/issues/40.  Once it is merged and released then update the dependencies.

**Comment by richardschneider** [comment]
@vmx All  IPLD formats (dag-cbor, dag-pb, raw, git, bitcoin, ethereum and zcash) are updated to support `cid-options`.  Can you release the packages to NPM?

**Comment by vmx** [comment]
@richardschneider When looking at e.g. js-ipld-bitcoin, I see that the options are ignored. I thought that's just a first step. I think silently ignoring options is a bad idea. It should either support `hashAlg`, or throw an error if it doesn't.

**Comment by richardschneider** [comment]
@vms ethereum is ready to go.  Can we get a new release?

**Comment by richardschneider** [comment]
@vmx why iis circle CI failing? Otherwise, ready for a merge and release.

```
W: GPG error: https://apt.dockerproject.org ubuntu-precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

sudo apt-get update returned exit code 100
```

**Comment by richardschneider** [comment]
@vmx Yeah team! are we now ready for a merge and release?

**Pull request merged**
