### PR TITLE
docs: add lead maintainer to package table

### PR DESCRIPTION
**Pull request by hacdias**
Add Lead Maintainer to Package table.

Ref.: https://github.com/ipfs-shipyard/package-table/issues/3

### CODE REVIEW

**Comment by mikeal** [comment]
Should the links be to their github profiles rather than `mailto:` links?

**Comment by hacdias** [comment]
@mikeal it would, indeed, be nice. Although that info isn't on the `leadMaintainer` field so I can't do it right now. We'd need to go through all repositories to update that

**Comment by diasdavid** [comment]
Yeah, agree with @mikeal that having the github profile would be more useful than an email but as @hacdias says, it would require to change all the repos. Please post that as a proposal for the [Lead Maintainer Protocol](https://github.com/ipfs/community/blob/master/js-code-guidelines.md#tech-leads-and-lead-maintainers).

Meanwhile, we can take this as is. It is already an increment.

**Comment by diasdavid** [comment]
Windows tests failed with `stderr: error: copy-fd: write returned: No space left on device`

**Pull request merged**
