### PR TITLE
Fix IPLD paths on Windows

### LINKED ISSUE #99: Usage of node `path.join` breaks IPLD paths on Windows
joinPath [here](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L115) is returning the path separated by platform-specific path separators.

The code afterwards in the resolvers is expecting forward slashes, so it doesn't work on Windows platforms.

I suggest replacing all backslashes by slashes after joinPath on Windows platforms.

### PR DESCRIPTION
**Pull request by Expyron**
Fixes #99

### CODE REVIEW

**Comment by richardschneider** [comment]
Thanks @Expyron for your PR.

The real problem is much deeper in the stack, see https://github.com/ipfs/interface-datastore/pull/12

When I get this all sorted out, I'll drop you note.

**Comment by richardschneider** [comment]
This is fixed in PR #104

**Comment by Expyron** [comment]
@richardschneider 

I still believe that this fix is better than what you used in PR #104 .

With the code in #104 , IPLD cannot resolve paths containing backslashes on Windows, making it have a different behavior than on Linux.

You can reproduce with (working on Linux, but not on Windows):
`let cid = await ipfs.dag.put({'\\test\\':'test'}, {format: 'dag-cbor'}).catch((err) => { console.log(err)})`
`let obj = (await ipfs.dag.get(cid, "\\test\\").catch((err) => { console.log(err)})).value`

**Comment by richardschneider** [comment]
I'm sorry, did not read your patch fully.  There's been lot's of issues/PRs for Windows.

I will take a look `ipfs.dag.put`.

cc @diasdavid

**Comment by diasdavid** [comment]
@richardschneider is this still a issue?

**Comment by richardschneider** [comment]
@diasdavid Just ran all the tests on windows and every test passed.

This PR is no longer required.

**Pull request closed without merging**
